/*
 * Copyright 2023 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORT0_29 (coord F8), DP4LANE
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DP4LANE_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DP4LANE_GPIO_PIN 29U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_DP4LANE_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DP4LANE_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DP4LANE_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DP4LANE_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORT1_23 (coord M4), DP_HPD
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DP_HPD_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DP_HPD_GPIO_PIN 23U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_DP_HPD_GPIO_PIN_MASK (1U << 23U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DP_HPD_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DP_HPD_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DP_HPD_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT0_30 (coord E7), EXTRA_EN_SRCn
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_EXTRA_EN_SRCn_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_EXTRA_EN_SRCn_GPIO_PIN 30U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_EXTRA_EN_SRCn_GPIO_PIN_MASK (1U << 30U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_EXTRA_EN_SRCn_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_EXTRA_EN_SRCn_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_EXTRA_EN_SRCn_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT1_21 (coord L5), P0_XSD
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_P0_XSD_GPIO GPIO1                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_P0_XSD_GPIO_PIN 21U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_P0_XSD_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_P0_XSD_PORT PORT1                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_P0_XSD_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_P0_XSD_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT1_2 (coord C4), DC_BARREL_PRES
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_DC_BARREL_PRES_GPIO GPIO1               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_DC_BARREL_PRES_GPIO_PIN 2U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_DC_BARREL_PRES_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_DC_BARREL_PRES_PORT PORT1               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_DC_BARREL_PRES_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DC_BARREL_PRES_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORT0_28 (coord E8), nALERT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_nALERT_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_nALERT_GPIO_PIN 28U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_nALERT_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_nALERT_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_nALERT_PIN 28U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_nALERT_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORT0_10 (coord B12), ORIENT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_ORIENT_GPIO GPIO0                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_ORIENT_GPIO_PIN 10U              /*!<@brief GPIO pin number */
#define BOARD_INITPINS_ORIENT_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_ORIENT_PORT PORT0                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_ORIENT_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_ORIENT_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void I2C2_InitPins(void);

/*!
 * @brief This is a de-initialization function for 'I2C2_InitPins' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 */
void I2C2_DeinitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
