/*
 * Copyright 2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */


/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v15.0
processor: MIMXRT798S
package_id: MIMXRT798SGFOA
mcu_data: ksdk2_0
processor_version: 0.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_iopctl.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: N4, peripheral: LP_FLEXCOMM0, signal: P0, pin_signal: PIO0_31, InvertInput: normal, OpenDrainEnable: disable, InputBufferEnable: enable, PullSelect: down,
    PullEnable: disable}
  - {pin_num: N5, peripheral: LP_FLEXCOMM0, signal: P1, pin_signal: PIO1_0, InvertInput: normal, OpenDrainEnable: disable, InputBufferEnable: disable, PullSelect: down,
    PullEnable: disable}
  - {pin_num: G4, peripheral: GPIO2, signal: 'IO, 8', pin_signal: PIO2_8, InvertInput: normal, OpenDrainEnable: disable, AnalogMuxEnable: digital, FullOutputDrive: normal,
    SlewRateControl: standard, InputBufferEnable: enable, PullSelect: up, PullEnable: enable}
  - {pin_num: H6, peripheral: GPIO2, signal: 'IO, 6', pin_signal: PIO2_6, InvertInput: normal, OpenDrainEnable: disable, AnalogMuxEnable: digital, FullOutputDrive: normal,
    SlewRateControl: standard, InputBufferEnable: enable, PullSelect: up, PullEnable: enable}
  - {pin_num: H2, peripheral: GPIO2, signal: 'IO, 0', pin_signal: PIO2_0, InvertInput: normal, OpenDrainEnable: disable, AnalogMuxEnable: digital, FullOutputDrive: normal,
    SlewRateControl: standard, InputBufferEnable: enable, PullSelect: up, PullEnable: enable}
  - {pin_num: D4, peripheral: GPIO2, signal: 'IO, 14', pin_signal: PIO2_14, InvertInput: normal, OpenDrainEnable: disable, AnalogMuxEnable: digital, FullOutputDrive: normal,
    SlewRateControl: standard, InputBufferEnable: enable, PullSelect: up, PullEnable: enable}
  - {pin_num: G2, peripheral: GPIO2, signal: 'IO, 1', pin_signal: PIO2_1, InvertInput: normal, OpenDrainEnable: disable, AnalogMuxEnable: digital, FullOutputDrive: normal,
    SlewRateControl: standard, InputBufferEnable: enable, PullSelect: up, PullEnable: enable}
  - {pin_num: G5, peripheral: GPIO2, signal: 'IO, 9', pin_signal: PIO2_9, InvertInput: normal, OpenDrainEnable: disable, AnalogMuxEnable: digital, FullOutputDrive: normal,
    SlewRateControl: standard, InputBufferEnable: enable, PullSelect: up, PullEnable: enable}
  - {pin_num: D3, peripheral: GPIO2, signal: 'IO, 15', pin_signal: PIO2_15, InvertInput: normal, OpenDrainEnable: disable, AnalogMuxEnable: digital, FullOutputDrive: normal,
    SlewRateControl: standard, InputBufferEnable: enable, PullSelect: up, PullEnable: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 (Core #0) */
void BOARD_InitPins(void)
{
    /* Reset IOPCTL0 module */
    RESET_ClearPeripheralReset(kIOPCTL0_RST_SHIFT_RSTn);

    const uint32_t port0_pin31_config = (/* Pin is configured as LP_FLEXCOMM0_P0 */
                                         IOPCTL_PIO_FUNC1 |
                                         /* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_DI |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Enables input buffer function */
                                         IOPCTL_PIO_INBUF_EN |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI |
                                         /* Selects transmitter current drive 100ohm */
                                         IOPCTL_PIO_DRIVE_100OHM);
    /* PORT0 PIN31 (coords: N4) is configured as LP_FLEXCOMM0_P0 */
    IOPCTL_PinMuxSet(0U, 31U, port0_pin31_config);

    const uint32_t port1_pin0_config = (/* Pin is configured as LP_FLEXCOMM0_P1 */
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI |
                                        /* Selects transmitter current drive 100ohm */
                                        IOPCTL_PIO_DRIVE_100OHM);
    /* PORT1 PIN0 (coords: N5) is configured as LP_FLEXCOMM0_P1 */
    IOPCTL_PinMuxSet(1U, 0U, port1_pin0_config);

    const uint32_t port2_pin0_config = (/* Pin is configured as GPIO2_IO0 */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Enable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_EN |
                                        /* Enable pull-up function */
                                        IOPCTL_PIO_PULLUP_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_FULLDRIVE_DI |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN0 (coords: H2) is configured as GPIO2_IO0 */
    IOPCTL_PinMuxSet(2U, 0U, port2_pin0_config);

    const uint32_t port2_pin1_config = (/* Pin is configured as GPIO2_IO1 */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Enable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_EN |
                                        /* Enable pull-up function */
                                        IOPCTL_PIO_PULLUP_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_FULLDRIVE_DI |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN1 (coords: G2) is configured as GPIO2_IO1 */
    IOPCTL_PinMuxSet(2U, 1U, port2_pin1_config);

    const uint32_t port2_pin14_config = (/* Pin is configured as GPIO2_IO14 */
                                         IOPCTL_PIO_FUNC0 |
                                         /* Enable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_EN |
                                         /* Enable pull-up function */
                                         IOPCTL_PIO_PULLUP_EN |
                                         /* Enables input buffer function */
                                         IOPCTL_PIO_INBUF_EN |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Normal drive */
                                         IOPCTL_PIO_FULLDRIVE_DI |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT2 PIN14 (coords: D4) is configured as GPIO2_IO14 */
    IOPCTL_PinMuxSet(2U, 14U, port2_pin14_config);

    const uint32_t port2_pin15_config = (/* Pin is configured as GPIO2_IO15 */
                                         IOPCTL_PIO_FUNC0 |
                                         /* Enable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_EN |
                                         /* Enable pull-up function */
                                         IOPCTL_PIO_PULLUP_EN |
                                         /* Enables input buffer function */
                                         IOPCTL_PIO_INBUF_EN |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Normal drive */
                                         IOPCTL_PIO_FULLDRIVE_DI |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT2 PIN15 (coords: D3) is configured as GPIO2_IO15 */
    IOPCTL_PinMuxSet(2U, 15U, port2_pin15_config);

    const uint32_t port2_pin6_config = (/* Pin is configured as GPIO2_IO6 */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Enable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_EN |
                                        /* Enable pull-up function */
                                        IOPCTL_PIO_PULLUP_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_FULLDRIVE_DI |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN6 (coords: H6) is configured as GPIO2_IO6 */
    IOPCTL_PinMuxSet(2U, 6U, port2_pin6_config);

    const uint32_t port2_pin8_config = (/* Pin is configured as GPIO2_IO8 */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Enable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_EN |
                                        /* Enable pull-up function */
                                        IOPCTL_PIO_PULLUP_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_FULLDRIVE_DI |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN8 (coords: G4) is configured as GPIO2_IO8 */
    IOPCTL_PinMuxSet(2U, 8U, port2_pin8_config);

    const uint32_t port2_pin9_config = (/* Pin is configured as GPIO2_IO9 */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Enable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_EN |
                                        /* Enable pull-up function */
                                        IOPCTL_PIO_PULLUP_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_FULLDRIVE_DI |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT2 PIN9 (coords: G5) is configured as GPIO2_IO9 */
    IOPCTL_PinMuxSet(2U, 9U, port2_pin9_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
LPI2C8_InitPins:
- options: {callFromInitBoot: 'false', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: K5, peripheral: LP_FLEXCOMM8, signal: P1, pin_signal: PIO0_7, InvertInput: normal, OpenDrainEnable: disable, InputBufferEnable: enable, PullSelect: up,
    PullEnable: enable}
  - {pin_num: J5, peripheral: LP_FLEXCOMM8, signal: P0, pin_signal: PIO0_6, InputBufferEnable: enable, PullSelect: up, PullEnable: enable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPI2C8_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 (Core #0) */
void LPI2C8_InitPins(void)
{
    /* Reset IOPCTL0 module */
    RESET_ClearPeripheralReset(kIOPCTL0_RST_SHIFT_RSTn);

    const uint32_t port0_pin6_config = (/* Pin is configured as LP_FLEXCOMM8_P0 */
                                        IOPCTL_PIO_FUNC5 |
                                        /* Enable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_EN |
                                        /* Enable pull-up function */
                                        IOPCTL_PIO_PULLUP_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI |
                                        /* Selects transmitter current drive 100ohm */
                                        IOPCTL_PIO_DRIVE_100OHM);
    /* PORT0 PIN6 (coords: J5) is configured as LP_FLEXCOMM8_P0 */
    IOPCTL_PinMuxSet(0U, 6U, port0_pin6_config);

    const uint32_t port0_pin7_config = (/* Pin is configured as LP_FLEXCOMM8_P1 */
                                        IOPCTL_PIO_FUNC5 |
                                        /* Enable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_EN |
                                        /* Enable pull-up function */
                                        IOPCTL_PIO_PULLUP_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI |
                                        /* Selects transmitter current drive 100ohm */
                                        IOPCTL_PIO_DRIVE_100OHM);
    /* PORT0 PIN7 (coords: K5) is configured as LP_FLEXCOMM8_P1 */
    IOPCTL_PinMuxSet(0U, 7U, port0_pin7_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
LPI2C8_DeinitPins:
- options: {callFromInitBoot: 'false', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: J5, peripheral: GPIO0, signal: 'IO, 6', pin_signal: PIO0_6, InvertInput: normal, OpenDrainEnable: disable, InputBufferEnable: disable, PullSelect: down,
    PullEnable: disable}
  - {pin_num: K5, peripheral: GPIO0, signal: 'IO, 7', pin_signal: PIO0_7, InvertInput: normal, OpenDrainEnable: disable, InputBufferEnable: disable, PullSelect: down,
    PullEnable: disable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPI2C8_DeinitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 (Core #0) */
void LPI2C8_DeinitPins(void)
{
    /* Reset IOPCTL0 module */
    RESET_ClearPeripheralReset(kIOPCTL0_RST_SHIFT_RSTn);

    const uint32_t port0_pin6_config = (/* Pin is configured as GPIO0_IO6 */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI |
                                        /* Selects transmitter current drive 100ohm */
                                        IOPCTL_PIO_DRIVE_100OHM);
    /* PORT0 PIN6 (coords: J5) is configured as GPIO0_IO6 */
    IOPCTL_PinMuxSet(0U, 6U, port0_pin6_config);

    const uint32_t port0_pin7_config = (/* Pin is configured as GPIO0_IO7 */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI |
                                        /* Selects transmitter current drive 100ohm */
                                        IOPCTL_PIO_DRIVE_100OHM);
    /* PORT0 PIN7 (coords: K5) is configured as GPIO0_IO7 */
    IOPCTL_PinMuxSet(0U, 7U, port0_pin7_config);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
