/*
 * Copyright 2023 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v14.0
processor: MCXN236
package_id: MCXN236VDF
mcu_data: ksdk2_0
processor_version: 0.14.4
pin_labels:
- {pin_num: A8, pin_signal: PIO0_21/FC0_P5/FC1_P1/CT_INP1/FLEXIO0_D5/I3C0_SCL/ADC0_A13, label: EXTRA_EN_SRCn, identifier: EXTRA_EN_SRCn}
- {pin_num: B7, pin_signal: PIO0_23/WUU0_IN5/EWM0_OUT_b/FC1_P3/CT_INP3/FLEXIO0_D7/ADC0_A15, label: nALERT, identifier: nALERT}
- {pin_num: H2, pin_signal: PIO2_0/TRIG_IN5/PWM1_A3/FLEXIO0_D8/SAI0_RX_BCLK, label: DP4LANE, identifier: DP4LANE}
- {pin_num: G16, pin_signal: PIO3_12/FC7_P4/FC6_P4/CT1_MAT2/PWM1_A0/FLEXIO0_D20/SAI0_RXD1, label: DP_HPD, identifier: DP_HPD}
- {pin_num: L2, pin_signal: PIO2_7/TRIG_IN5/PWM1_B0/FLEXIO0_D15/SAI0_TX_FS, label: P0_XSD, identifier: P0_XSD}
- {pin_num: K15, pin_signal: PIO3_17/WUU0_IN26/CT_INP9/PWM1_B2/FLEXIO0_D25/SAI1_TX_FS, label: DC_BARREL_PRES, identifier: DC_BARREL_PRES}
- {pin_num: H17, pin_signal: PIO3_14/WUU0_IN25/CT_INP6/PWM1_A1/FLEXIO0_D22/SAI0_RX_BCLK, label: ORIENT, identifier: ORIENT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33_core0, enableClock: 'true'}
- pin_list:
  - {pin_num: A1, peripheral: LP_FLEXCOMM4, signal: LPFLEXCOMM_P0, pin_signal: PIO1_8/WUU0_IN10/LPTMR1_ALT3/TRACE_DATA0/FC4_P0/FC5_P4/CT_INP8/FLEXIO0_D16/I3C1_SDA/ADC1_A8,
    eft_interrupt: disable, slew_rate: fast, open_drain: disable, drive_strength: low, pull_enable: disable, passive_filter: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: B1, peripheral: LP_FLEXCOMM4, signal: LPFLEXCOMM_P1, pin_signal: PIO1_9/TRACE_DATA1/FC4_P1/FC5_P5/CT_INP9/FLEXIO0_D17/I3C1_SCL/ADC1_A9, eft_interrupt: disable,
    slew_rate: fast, open_drain: disable, drive_strength: low, pull_enable: disable, passive_filter: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: H2, peripheral: GPIO2, signal: 'GPIO, 0', pin_signal: PIO2_0/TRIG_IN5/PWM1_A3/FLEXIO0_D8/SAI0_RX_BCLK, direction: OUTPUT, eft_interrupt: disable, slew_rate: fast,
    open_drain: disable, drive_strength: high, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: G16, peripheral: GPIO3, signal: 'GPIO, 12', pin_signal: PIO3_12/FC7_P4/FC6_P4/CT1_MAT2/PWM1_A0/FLEXIO0_D20/SAI0_RXD1, direction: OUTPUT, eft_interrupt: disable,
    slew_rate: fast, open_drain: disable, drive_strength: high, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: A8, peripheral: GPIO0, signal: 'GPIO, 21', pin_signal: PIO0_21/FC0_P5/FC1_P1/CT_INP1/FLEXIO0_D5/I3C0_SCL/ADC0_A13, direction: OUTPUT, eft_interrupt: disable,
    slew_rate: fast, open_drain: disable, drive_strength: high, pull_enable: disable, passive_filter: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: L2, peripheral: GPIO2, signal: 'GPIO, 7', pin_signal: PIO2_7/TRIG_IN5/PWM1_B0/FLEXIO0_D15/SAI0_TX_FS, direction: OUTPUT, eft_interrupt: disable, slew_rate: fast,
    open_drain: disable, drive_strength: high, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: K15, peripheral: GPIO3, signal: 'GPIO, 17', pin_signal: PIO3_17/WUU0_IN26/CT_INP9/PWM1_B2/FLEXIO0_D25/SAI1_TX_FS, direction: INPUT, eft_interrupt: disable,
    slew_rate: fast, open_drain: disable, drive_strength: high, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: B7, peripheral: GPIO0, signal: 'GPIO, 23', pin_signal: PIO0_23/WUU0_IN5/EWM0_OUT_b/FC1_P3/CT_INP3/FLEXIO0_D7/ADC0_A15, direction: INPUT, eft_interrupt: disable,
    slew_rate: fast, open_drain: disable, drive_strength: high, pull_enable: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: H17, peripheral: GPIO3, signal: 'GPIO, 14', pin_signal: PIO3_14/WUU0_IN25/CT_INP6/PWM1_A1/FLEXIO0_D22/SAI0_RX_BCLK, direction: OUTPUT, eft_interrupt: disable,
    slew_rate: fast, open_drain: disable, drive_strength: high, pull_enable: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Enables the clock for GPIO0: Enables clock */
    CLOCK_EnableClock(kCLOCK_Gpio0);
    /* Enables the clock for GPIO2: Enables clock */
    CLOCK_EnableClock(kCLOCK_Gpio2);
    /* Enables the clock for GPIO3: Enables clock */
    CLOCK_EnableClock(kCLOCK_Gpio3);
    /* Enables the clock for PORT0 controller: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port0);
    /* Enables the clock for PORT1: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port1);
    /* Enables the clock for PORT2: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port2);
    /* Enables the clock for PORT3: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port3);

    gpio_pin_config_t EXTRA_EN_SRCn_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_21 (pin A8)  */
    GPIO_PinInit(BOARD_INITPINS_EXTRA_EN_SRCn_GPIO, BOARD_INITPINS_EXTRA_EN_SRCn_PIN, &EXTRA_EN_SRCn_config);

    gpio_pin_config_t nALERT_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO0_23 (pin B7)  */
    GPIO_PinInit(BOARD_INITPINS_nALERT_GPIO, BOARD_INITPINS_nALERT_PIN, &nALERT_config);

    gpio_pin_config_t DP4LANE_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_0 (pin H2)  */
    GPIO_PinInit(BOARD_INITPINS_DP4LANE_GPIO, BOARD_INITPINS_DP4LANE_PIN, &DP4LANE_config);

    gpio_pin_config_t P0_XSD_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO2_7 (pin L2)  */
    GPIO_PinInit(BOARD_INITPINS_P0_XSD_GPIO, BOARD_INITPINS_P0_XSD_PIN, &P0_XSD_config);

    gpio_pin_config_t DP_HPD_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_12 (pin G16)  */
    GPIO_PinInit(BOARD_INITPINS_DP_HPD_GPIO, BOARD_INITPINS_DP_HPD_PIN, &DP_HPD_config);

    gpio_pin_config_t ORIENT_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_14 (pin H17)  */
    GPIO_PinInit(BOARD_INITPINS_ORIENT_GPIO, BOARD_INITPINS_ORIENT_PIN, &ORIENT_config);

    gpio_pin_config_t DC_BARREL_PRES_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PIO3_17 (pin K15)  */
    GPIO_PinInit(BOARD_INITPINS_DC_BARREL_PRES_GPIO, BOARD_INITPINS_DC_BARREL_PRES_PIN, &DC_BARREL_PRES_config);

    /* EFT detect interrupts configuration on PORT0_ */
    PORT_DisableEFTDetectInterrupts(PORT0, 0xA00000u);

    /* PORT0_21 (pin A8) is configured as PIO0_21 */
    PORT_SetPinMux(BOARD_INITPINS_EXTRA_EN_SRCn_PORT, BOARD_INITPINS_EXTRA_EN_SRCn_PIN, kPORT_MuxAlt0);

    PORT0->PCR[21] =
        ((PORT0->PCR[21] &
          /* Mask bits to zero which are setting */
          (~(PORT_PCR_PE_MASK | PORT_PCR_SRE_MASK | PORT_PCR_PFE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_IBE_MASK | PORT_PCR_INV_MASK)))

         /* Pull Enable: Disables. */
         | PORT_PCR_PE(PCR_PE_pe0)

         /* Slew Rate Enable: Fast. */
         | PORT_PCR_SRE(PCR_SRE_sre0)

         /* Passive Filter Enable: Disables. */
         | PORT_PCR_PFE(PCR_PFE_pfe0)

         /* Open Drain Enable: Disables. */
         | PORT_PCR_ODE(PCR_ODE_ode0)

         /* Drive Strength Enable: High. */
         | PORT_PCR_DSE(PCR_DSE_dse1)

         /* Input Buffer Enable: Enables. */
         | PORT_PCR_IBE(PCR_IBE_ibe1)

         /* Invert Input: Does not invert. */
         | PORT_PCR_INV(PCR_INV_inv0));

    /* PORT0_23 (pin B7) is configured as PIO0_23 */
    PORT_SetPinMux(BOARD_INITPINS_nALERT_PORT, BOARD_INITPINS_nALERT_PIN, kPORT_MuxAlt0);

    PORT0->PCR[23] =
        ((PORT0->PCR[23] &
          /* Mask bits to zero which are setting */
          (~(PORT_PCR_PE_MASK | PORT_PCR_SRE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_IBE_MASK | PORT_PCR_INV_MASK)))

         /* Pull Enable: Disables. */
         | PORT_PCR_PE(PCR_PE_pe0)

         /* Slew Rate Enable: Fast. */
         | PORT_PCR_SRE(PCR_SRE_sre0)

         /* Open Drain Enable: Disables. */
         | PORT_PCR_ODE(PCR_ODE_ode0)

         /* Drive Strength Enable: High. */
         | PORT_PCR_DSE(PCR_DSE_dse1)

         /* Input Buffer Enable: Enables. */
         | PORT_PCR_IBE(PCR_IBE_ibe1)

         /* Invert Input: Does not invert. */
         | PORT_PCR_INV(PCR_INV_inv0));

    /* EFT detect interrupts configuration on PORT1_ */
    PORT_DisableEFTDetectInterrupts(PORT1, 0x0300u);

    /* PORT1_8 (pin A1) is configured as FC4_P0 */
    PORT_SetPinMux(PORT1, 8U, kPORT_MuxAlt2);

    PORT1->PCR[8] =
        ((PORT1->PCR[8] &
          /* Mask bits to zero which are setting */
          (~(PORT_PCR_PE_MASK | PORT_PCR_SRE_MASK | PORT_PCR_PFE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_IBE_MASK | PORT_PCR_INV_MASK)))

         /* Pull Enable: Disables. */
         | PORT_PCR_PE(PCR_PE_pe0)

         /* Slew Rate Enable: Fast. */
         | PORT_PCR_SRE(PCR_SRE_sre0)

         /* Passive Filter Enable: Disables. */
         | PORT_PCR_PFE(PCR_PFE_pfe0)

         /* Open Drain Enable: Disables. */
         | PORT_PCR_ODE(PCR_ODE_ode0)

         /* Drive Strength Enable: Low. */
         | PORT_PCR_DSE(PCR_DSE_dse0)

         /* Input Buffer Enable: Enables. */
         | PORT_PCR_IBE(PCR_IBE_ibe1)

         /* Invert Input: Does not invert. */
         | PORT_PCR_INV(PCR_INV_inv0));

    /* PORT1_9 (pin B1) is configured as FC4_P1 */
    PORT_SetPinMux(PORT1, 9U, kPORT_MuxAlt2);

    PORT1->PCR[9] =
        ((PORT1->PCR[9] &
          /* Mask bits to zero which are setting */
          (~(PORT_PCR_PE_MASK | PORT_PCR_SRE_MASK | PORT_PCR_PFE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_IBE_MASK | PORT_PCR_INV_MASK)))

         /* Pull Enable: Disables. */
         | PORT_PCR_PE(PCR_PE_pe0)

         /* Slew Rate Enable: Fast. */
         | PORT_PCR_SRE(PCR_SRE_sre0)

         /* Passive Filter Enable: Disables. */
         | PORT_PCR_PFE(PCR_PFE_pfe0)

         /* Open Drain Enable: Disables. */
         | PORT_PCR_ODE(PCR_ODE_ode0)

         /* Drive Strength Enable: Low. */
         | PORT_PCR_DSE(PCR_DSE_dse0)

         /* Input Buffer Enable: Enables. */
         | PORT_PCR_IBE(PCR_IBE_ibe1)

         /* Invert Input: Does not invert. */
         | PORT_PCR_INV(PCR_INV_inv0));

    /* EFT detect interrupts configuration on PORT2_ */
    PORT_DisableEFTDetectInterrupts(PORT2, 0x81u);

    /* PORT2_0 (pin H2) is configured as PIO2_0 */
    PORT_SetPinMux(BOARD_INITPINS_DP4LANE_PORT, BOARD_INITPINS_DP4LANE_PIN, kPORT_MuxAlt0);

    PORT2->PCR[0] =
        ((PORT2->PCR[0] &
          /* Mask bits to zero which are setting */
          (~(PORT_PCR_PE_MASK | PORT_PCR_SRE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_IBE_MASK | PORT_PCR_INV_MASK)))

         /* Pull Enable: Disables. */
         | PORT_PCR_PE(PCR_PE_pe0)

         /* Slew Rate Enable: Fast. */
         | PORT_PCR_SRE(PCR_SRE_sre0)

         /* Open Drain Enable: Disables. */
         | PORT_PCR_ODE(PCR_ODE_ode0)

         /* Drive Strength Enable: High. */
         | PORT_PCR_DSE(PCR_DSE_dse1)

         /* Input Buffer Enable: Enables. */
         | PORT_PCR_IBE(PCR_IBE_ibe1)

         /* Invert Input: Does not invert. */
         | PORT_PCR_INV(PCR_INV_inv0));

    /* PORT2_7 (pin L2) is configured as PIO2_7 */
    PORT_SetPinMux(BOARD_INITPINS_P0_XSD_PORT, BOARD_INITPINS_P0_XSD_PIN, kPORT_MuxAlt0);

    PORT2->PCR[7] =
        ((PORT2->PCR[7] &
          /* Mask bits to zero which are setting */
          (~(PORT_PCR_PE_MASK | PORT_PCR_SRE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_IBE_MASK | PORT_PCR_INV_MASK)))

         /* Pull Enable: Disables. */
         | PORT_PCR_PE(PCR_PE_pe0)

         /* Slew Rate Enable: Fast. */
         | PORT_PCR_SRE(PCR_SRE_sre0)

         /* Open Drain Enable: Disables. */
         | PORT_PCR_ODE(PCR_ODE_ode0)

         /* Drive Strength Enable: High. */
         | PORT_PCR_DSE(PCR_DSE_dse1)

         /* Input Buffer Enable: Enables. */
         | PORT_PCR_IBE(PCR_IBE_ibe1)

         /* Invert Input: Does not invert. */
         | PORT_PCR_INV(PCR_INV_inv0));

    /* EFT detect interrupts configuration on PORT3_ */
    PORT_DisableEFTDetectInterrupts(PORT3, 0x025000u);

    /* PORT3_12 (pin G16) is configured as PIO3_12 */
    PORT_SetPinMux(BOARD_INITPINS_DP_HPD_PORT, BOARD_INITPINS_DP_HPD_PIN, kPORT_MuxAlt0);

    PORT3->PCR[12] =
        ((PORT3->PCR[12] &
          /* Mask bits to zero which are setting */
          (~(PORT_PCR_PE_MASK | PORT_PCR_SRE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_IBE_MASK | PORT_PCR_INV_MASK)))

         /* Pull Enable: Disables. */
         | PORT_PCR_PE(PCR_PE_pe0)

         /* Slew Rate Enable: Fast. */
         | PORT_PCR_SRE(PCR_SRE_sre0)

         /* Open Drain Enable: Disables. */
         | PORT_PCR_ODE(PCR_ODE_ode0)

         /* Drive Strength Enable: High. */
         | PORT_PCR_DSE(PCR_DSE_dse1)

         /* Input Buffer Enable: Enables. */
         | PORT_PCR_IBE(PCR_IBE_ibe1)

         /* Invert Input: Does not invert. */
         | PORT_PCR_INV(PCR_INV_inv0));

    /* PORT3_14 (pin H17) is configured as PIO3_14 */
    PORT_SetPinMux(BOARD_INITPINS_ORIENT_PORT, BOARD_INITPINS_ORIENT_PIN, kPORT_MuxAlt0);

    PORT3->PCR[14] =
        ((PORT3->PCR[14] &
          /* Mask bits to zero which are setting */
          (~(PORT_PCR_PE_MASK | PORT_PCR_SRE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_IBE_MASK | PORT_PCR_INV_MASK)))

         /* Pull Enable: Disables. */
         | PORT_PCR_PE(PCR_PE_pe0)

         /* Slew Rate Enable: Fast. */
         | PORT_PCR_SRE(PCR_SRE_sre0)

         /* Open Drain Enable: Disables. */
         | PORT_PCR_ODE(PCR_ODE_ode0)

         /* Drive Strength Enable: High. */
         | PORT_PCR_DSE(PCR_DSE_dse1)

         /* Input Buffer Enable: Enables. */
         | PORT_PCR_IBE(PCR_IBE_ibe1)

         /* Invert Input: Does not invert. */
         | PORT_PCR_INV(PCR_INV_inv0));

    /* PORT3_17 (pin K15) is configured as PIO3_17 */
    PORT_SetPinMux(BOARD_INITPINS_DC_BARREL_PRES_PORT, BOARD_INITPINS_DC_BARREL_PRES_PIN, kPORT_MuxAlt0);

    PORT3->PCR[17] =
        ((PORT3->PCR[17] &
          /* Mask bits to zero which are setting */
          (~(PORT_PCR_PE_MASK | PORT_PCR_SRE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_IBE_MASK | PORT_PCR_INV_MASK)))

         /* Pull Enable: Disables. */
         | PORT_PCR_PE(PCR_PE_pe0)

         /* Slew Rate Enable: Fast. */
         | PORT_PCR_SRE(PCR_SRE_sre0)

         /* Open Drain Enable: Disables. */
         | PORT_PCR_ODE(PCR_ODE_ode0)

         /* Drive Strength Enable: High. */
         | PORT_PCR_DSE(PCR_DSE_dse1)

         /* Input Buffer Enable: Enables. */
         | PORT_PCR_IBE(PCR_IBE_ibe1)

         /* Invert Input: Does not invert. */
         | PORT_PCR_INV(PCR_INV_inv0));
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
I2C2_InitPins:
- options: {createDeInit: 'true', callFromInitBoot: 'false', coreID: cm33_core0, enableClock: 'true', customDeInitName: I2C2_DeinitPins}
- pin_list:
  - {pin_num: F6, peripheral: LP_FLEXCOMM5, signal: LPFLEXCOMM_P0, pin_signal: PIO1_16/WUU0_IN14/FC5_P0/FC3_P4/CT_INP12/FLEXIO0_D24/I3C1_SDA/ADC1_A16, eft_interrupt: disable,
    slew_rate: fast, open_drain: disable, drive_strength: high, pull_enable: disable, passive_filter: disable, input_buffer: enable, invert_input: normal}
  - {pin_num: F4, peripheral: LP_FLEXCOMM5, signal: LPFLEXCOMM_P1, pin_signal: PIO1_17/FC5_P1/FC3_P5/CT_INP13/FLEXIO0_D25/I3C1_SCL/ADC1_A17, eft_interrupt: disable,
    slew_rate: fast, open_drain: disable, drive_strength: high, pull_enable: disable, passive_filter: disable, input_buffer: enable, invert_input: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : I2C2_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void I2C2_InitPins(void)
{
    /* Enables the clock for PORT1: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port1);

    /* EFT detect interrupts configuration on PORT1_ */
    PORT_DisableEFTDetectInterrupts(PORT1, 0x030000u);

    /* PORT1_16 (pin F6) is configured as FC5_P0 */
    PORT_SetPinMux(PORT1, 16U, kPORT_MuxAlt2);

    PORT1->PCR[16] =
        ((PORT1->PCR[16] &
          /* Mask bits to zero which are setting */
          (~(PORT_PCR_PE_MASK | PORT_PCR_SRE_MASK | PORT_PCR_PFE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_IBE_MASK | PORT_PCR_INV_MASK)))

         /* Pull Enable: Disables. */
         | PORT_PCR_PE(PCR_PE_pe0)

         /* Slew Rate Enable: Fast. */
         | PORT_PCR_SRE(PCR_SRE_sre0)

         /* Passive Filter Enable: Disables. */
         | PORT_PCR_PFE(PCR_PFE_pfe0)

         /* Open Drain Enable: Disables. */
         | PORT_PCR_ODE(PCR_ODE_ode0)

         /* Drive Strength Enable: High. */
         | PORT_PCR_DSE(PCR_DSE_dse1)

         /* Input Buffer Enable: Enables. */
         | PORT_PCR_IBE(PCR_IBE_ibe1)

         /* Invert Input: Does not invert. */
         | PORT_PCR_INV(PCR_INV_inv0));

    /* PORT1_17 (pin F4) is configured as FC5_P1 */
    PORT_SetPinMux(PORT1, 17U, kPORT_MuxAlt2);

    PORT1->PCR[17] =
        ((PORT1->PCR[17] &
          /* Mask bits to zero which are setting */
          (~(PORT_PCR_PE_MASK | PORT_PCR_SRE_MASK | PORT_PCR_PFE_MASK | PORT_PCR_ODE_MASK | PORT_PCR_DSE_MASK | PORT_PCR_IBE_MASK | PORT_PCR_INV_MASK)))

         /* Pull Enable: Disables. */
         | PORT_PCR_PE(PCR_PE_pe0)

         /* Slew Rate Enable: Fast. */
         | PORT_PCR_SRE(PCR_SRE_sre0)

         /* Passive Filter Enable: Disables. */
         | PORT_PCR_PFE(PCR_PFE_pfe0)

         /* Open Drain Enable: Disables. */
         | PORT_PCR_ODE(PCR_ODE_ode0)

         /* Drive Strength Enable: High. */
         | PORT_PCR_DSE(PCR_DSE_dse1)

         /* Input Buffer Enable: Enables. */
         | PORT_PCR_IBE(PCR_IBE_ibe1)

         /* Invert Input: Does not invert. */
         | PORT_PCR_INV(PCR_INV_inv0));
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : I2C2_DeinitPins
 * Description   : This is a de-initialization function for 'I2C2_InitPins' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 * END ****************************************************************************************************************/
void I2C2_DeinitPins(void)
{
    /* Enables the clock for PORT1: Enables clock */
    CLOCK_EnableClock(kCLOCK_Port1);

    /* EFT detect interrupts configuration on PORT1_ */
    PORT_DisableEFTDetectInterrupts(PORT1, 0x030000u);

    const port_pin_config_t port1_16_pinF6_config = {/* Internal pull-up/down resistor is disabled */
                                                     kPORT_PullDisable,
                                                     /* Low internal pull resistor value is selected. */
                                                     kPORT_LowPullResistor,
                                                     /* Fast slew rate is configured */
                                                     kPORT_FastSlewRate,
                                                     /* Passive input filter is disabled */
                                                     kPORT_PassiveFilterDisable,
                                                     /* Open drain output is disabled */
                                                     kPORT_OpenDrainDisable,
                                                     /* Low drive strength is configured */
                                                     kPORT_LowDriveStrength,
                                                     /* Pin is configured as ADC1_A16 */
                                                     kPORT_MuxAlt0,
                                                     /* Digital input disabled; it is required for analog functions */
                                                     kPORT_InputBufferDisable,
                                                     /* Digital input is not inverted */
                                                     kPORT_InputNormal,
                                                     /* Pin Control Register fields [15:0] are not locked */
                                                     kPORT_UnlockRegister};
    /* PORT1_16 (pin F6) is configured as ADC1_A16 */
    PORT_SetPinConfig(PORT1, 16U, &port1_16_pinF6_config);

    const port_pin_config_t port1_17_pinF4_config = {/* Internal pull-up/down resistor is disabled */
                                                     kPORT_PullDisable,
                                                     /* Low internal pull resistor value is selected. */
                                                     kPORT_LowPullResistor,
                                                     /* Fast slew rate is configured */
                                                     kPORT_FastSlewRate,
                                                     /* Passive input filter is disabled */
                                                     kPORT_PassiveFilterDisable,
                                                     /* Open drain output is disabled */
                                                     kPORT_OpenDrainDisable,
                                                     /* Low drive strength is configured */
                                                     kPORT_LowDriveStrength,
                                                     /* Pin is configured as ADC1_A17 */
                                                     kPORT_MuxAlt0,
                                                     /* Digital input disabled; it is required for analog functions */
                                                     kPORT_InputBufferDisable,
                                                     /* Digital input is not inverted */
                                                     kPORT_InputNormal,
                                                     /* Pin Control Register fields [15:0] are not locked */
                                                     kPORT_UnlockRegister};
    /* PORT1_17 (pin F4) is configured as ADC1_A17 */
    PORT_SetPinConfig(PORT1, 17U, &port1_17_pinF4_config);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
